### ISSUE TITLE
Release 0.1.1 Tracker

### ISSUE THREAD

**Issue by oke-aditya** [Quick-AI/quickvision#75]
## 🚀 Release

In parallel to release of PyTorch 1.7.1 and torchvision 0.8.2.
Quickvision release 0.1.1 will make it possible to use with these two.

We should try to keep release 0.1.x in consistent with PyTorch 1.7.x and torchvision 0.8.x
This will apply to future release as well subsequently.

Plan of release
- [x] Bump CI tests for new PyTorch and torchvision
- [x] Bump our verisions and release rc1.
- [x] CI Tests over CPU and GPU with new pytorch and torchvision
- [x] Test Notebooks and examples
- [x] Pin Lightning to v1.1.
- [x] CI Test with Lightning v1.1, PyTorch 1.7.1, torchvision 0.8.2.
- [x] Test stuff over GPU.
- [x] Release rc2.
- [x] Release rc3.
- [x] Ensure everything works fine, wait till major systems jump to new PyTorch (2 days waiting period)
- [ ] Release 0.1.1.

**Comment by oke-aditya** [comment]
PyTorch 1.7.1 will be stable this week, so I tihnk this release will be in next week.
